### ISSUE TITLE
NatShare payload cannot commit media on S10 Note+

### ISSUE THREAD

**Issue by Liam-Fologram** [natsuite/NatShare-API#80]
Save payload does not correctly commit media on the Samsung S10 Note+, this has been tested on multiple other android & iOS devices with no issues.

It seems attempting to save any kind of media via the payload (even if it successfully records) 

```
using (var payload = new NatShare.SavePayload(
    album: "Test Album", 
    completionHandler: () => Debug.Log("Saved Successfully")))
{
    payload.AddMedia(filepath);
}

Handheld.PlayFullScreenMovie(filepath); // this works, assuring the file exists and is not corrupt.
```

doing this gives us an error inside NatShare

`E/Unity: NatShare Error: SavePayload failed to commit media with error: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Fologram/recording_2020_02_18_11_04_35_841.mp4: open failed: EACCES (Permission denied)`

The device has all external write / read permissions.

[Logcat.txt](https://github.com/natsuite/NatShare-API/files/4216787/Logcat.txt)

**Comment by olokobayusuf** [comment]
Hey man, do you have access to the full (unfiltered) logs? There should be more information immediately before the "NatShare Error: ..." line.

**Comment by Liam-Fologram** [comment]
Of course, here is a full log output from a different build, same errors committing mp4 and png files.

[Full Logcat.txt](https://github.com/natsuite/NatShare-API/files/4222559/Full.Logcat.txt)

**Comment by olokobayusuf** [comment]
The logs don't seem to have any more information than "permission denied". Go into settings and make sure that your app in fact has the ability to write to external storage. Adding this to the app's manifest is not enough.

**Comment by Liam-Fologram** [comment]
I do checks at app startup, not allowing the user to use the application until they give us Camera, Microphone and Storage permissions.

I also do a check immediately before recording like this:

```
if (!Permission.HasUserAuthorizedPermission(Permission.ExternalStorageWrite))
{
   Notification.Show("Cannot record without Storage permissions.");
   return false;
}
```

and likewise for external storage read.

**Comment by Liam-Fologram** [comment]
@olokobayusuf I figured out whats going on for both this issue and issue #78. It seems this has nothing to do with any recent update and can be replicated on older versions of NatShare (I tested this issue on version 1.1 and it still failed as described with the same error)

With Android 10 (API 29 or higher) accessing parts of other applications or parts of the system now requires you to use the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider). I'm not sure exactly where in your code you need to use the SAF but this should help you solve the issue.

For people who need a solution now you can simply put a flag in your manifest file to request Android to use the legacy file access system.
```
<manifest ... >
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>
```

To do this:
- Copy Android manifest from `Unity Project/Temp/StagingArea/AndroidManifest.xml` to `Unity Project/Assests/Plugins/Android` (file names **must** match for Unity to merge your manifest with the generated one)
- In your manifest file in your Plugins folder add the attribute `android:requestLegacyExternalStorage="true"` to your `application` tag.

Your application should commit photos and videos correctly.

**Comment by olokobayusuf** [comment]
I've added a fix in #83, specifically 379ec036890bd69b17f242feb59cb7f8e5884e0a.

**Comment by derwaldgeist** [comment]
Hi, I ran into the same problem on a Galaxy S10 5G. Has this fix already been pushed to a new version of this package?

```log
2020-06-28 11:14:48.577 6503-6990/com.marblear.prototype.staging E/AndroidRuntime: FATAL EXCEPTION: SavePayload Commit Thread
    Process: com.marblear.prototype.staging, PID: 6503
    java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=6503, uid=10231 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
        at android.content.ContentResolver.insert(ContentResolver.java:1594)
        at api.natsuite.natshare.SavePayload.lambda$commit$0$SavePayload(SavePayload.java:90)
        at api.natsuite.natshare.-$$Lambda$SavePayload$0wjtSNJuMX77rkaraI8nWQBBikI.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by derwaldgeist** [comment]
Update: I downloaded the latest version from the Unity App Store, which also says 1.2.3, but seems to have some changes. Maybe I had tried a version from the repo before.

But still, the problem occurs on my Samsung S10 5G:

```
2020-06-28 11:41:44.270 13060-13782/com.marblear.prototype.staging E/AndroidRuntime: FATAL EXCEPTION: SavePayload Commit Thread
    Process: com.marblear.prototype.staging, PID: 13060
    java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=13060, uid=10231 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
        at android.content.ContentResolver.insert(ContentResolver.java:1594)
        at api.natsuite.natshare.SavePayload.lambda$commit$0$SavePayload(SavePayload.java:90)
        at api.natsuite.natshare.-$$Lambda$SavePayload$0wjtSNJuMX77rkaraI8nWQBBikI.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by derwaldgeist** [comment]
@Liam-Fologram 

> In your manifest file in your Plugins folder add the attribute android:requestLegacyExternalStorage="true" to your application tag.

How did you do this? My Android studio won't recognize this flag on the application tag.

**Comment by olokobayusuf** [comment]
I replied to #94. You need to enable external write access in player settings.
